version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/ssl:/etc/nginx/ssl:ro
    restart: always
    networks:
      - inception

  wordpress:
    env_file:
    - .env
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:inception
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/credentials
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_PASSWORD_FILE=/run/secrets/credentials
      - WP_EMAIL=${WP_EMAIL}
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_password
      - credentials
    restart: always
    networks:
      - inception

  mariadb:
    env_file:
    - .env
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: /run/secrets/db_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jmaruffy/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jmaruffy/data/mariadb

networks:
  inception:
    driver: bridge